export enum PasteType {
    PASTE_NORMAL = "PASTE_NORMAL",
    PASTE_VALUES = "PASTE_VALUES",
    PASTE_FORMAT = "PASTE_FORMAT",
    PASTE_NO_BORDERS = "PASTE_NO_BORDERS",
    PASTE_FORMULA = "PASTE_FORMULA",
    PASTE_DATA_VALIDATION = "PASTE_DATA_VALIDATION",
    PASTE_CONDITIONAL_FORMATTING = "PASTE_CONDITIONAL_FORMATTING",
}

export enum PasteOrientation {
    NORMAL = "NORMAL",
    TRANSPOSE = "TRANSPOSE",
}

export enum Dimension {
    DIMENSION_UNSPECIFIED = "DIMENSION_UNSPECIFIED",
    ROWS = "ROWS",
    COLUMNS = "COLUMNS",
}

export enum ConditionType {
    CONDITION_TYPE_UNSPECIFIED = "CONDITION_TYPE_UNSPECIFIED",
    NUMBER_GREATER = "NUMBER_GREATER",
    NUMBER_GREATER_THAN_EQ = "NUMBER_GREATER_THAN_EQ",
    NUMBER_LESS = "NUMBER_LESS",
    NUMBER_LESS_THAN_EQ = "NUMBER_LESS_THAN_EQ",
    NUMBER_EQ = "NUMBER_EQ",
    NUMBER_NOT_EQ = "NUMBER_NOT_EQ",
    NUMBER_BETWEEN = "NUMBER_BETWEEN",
    NUMBER_NOT_BETWEEN = "NUMBER_NOT_BETWEEN",
    TEXT_CONTAINS = "TEXT_CONTAINS",
    TEXT_NOT_CONTAINS = "TEXT_NOT_CONTAINS",
    TEXT_STARTS_WITH = "TEXT_STARTS_WITH",
    TEXT_ENDS_WITH = "TEXT_ENDS_WITH",
    TEXT_EQ = "TEXT_EQ",
    TEXT_IS_EMAIL = "TEXT_IS_EMAIL",
    TEXT_IS_URL = "TEXT_IS_URL",
    DATE_EQ = "DATE_EQ",
    DATE_BEFORE = "DATE_BEFORE",
    DATE_AFTER = "DATE_AFTER",
    DATE_ON_OR_BEFORE = "DATE_ON_OR_BEFORE",
    DATE_ON_OR_AFTER = "DATE_ON_OR_AFTER",
    DATE_BETWEEN = "DATE_BETWEEN",
    DATE_NOT_BETWEEN = "DATE_NOT_BETWEEN",
    DATE_IS_VALID = "DATE_IS_VALID",
    ONE_OF_RANGE = "ONE_OF_RANGE",
    ONE_OF_LIST = "ONE_OF_LIST",
    BLANK = "BLANK",
    NOT_BLANK = "NOT_BLANK",
    CUSTOM_FORMULA = "CUSTOM_FORMULA",
    BOOLEAN = "BOOLEAN",
    TEXT_NOT_EQ = "TEXT_NOT_EQ",
    DATE_NOT_EQ = "DATE_NOT_EQ",
    FILTER_EXPRESSION = "FILTER_EXPRESSION",
}

export enum MergeType {
    MERGE_ALL = "MERGE_ALL",
    MERGE_COLUMNS = "MERGE_COLUMNS",
    MERGE_ROWS = "MERGE_ROWS",
}

export enum ValueInputOption {
    INPUT_VALUE_OPTION_UNSPECIFIED = "INPUT_VALUE_OPTION_UNSPECIFIED",
    RAW = "RAW",
    USER_ENTERED = "USER_ENTERED",
}
