export const SetupSheetSchema = {
    templateId: "19WMef0XLfSNkK48IQDQ1WUxeLa4Ir1LfvHZ4W5xEiIk",
    sheetNames: {
        groupData: "Registro Inicial",
        calendarTemplate: "Template_Calendario",
        calendar: "Calendario",
    },
    namedRanges: {
        groupName: "datos_grupo",
        attendancePerClass: "datos_asistenciaIndividual",
        averagePerField: "datos_promedioPorCampos",
        dateStart: "datos_fechaInicio",
        dateTrimester1: "datos_trimestre1",
        dateTrimester2: "datos_trimestre2",
        dateEnd: "datos_fechaFin",
        subjects: "datos_asignaturas",
        students: "datos_estudiantes",
        monthNames1: "cal_mesAltura1",
        monthNames2: "cal_mesAltura2",
        monthNames3: "cal_mesAltura3",
        trimester1Day: "cal_diaTrimestre1",
        trimester2Day: "cal_diaTrimestre2",
        trimester3Day: "cal_diaTrimestre3",
        restDay: "cal_diaDescanso",
    },
} as const;
